### ISSUE TITLE
Collaboration

### ISSUE THREAD

**Issue by DanConwayDev** [gnostr-org/gnostr#126]
@RandyMcMillan

I'm, the author of ngit-cli and gitworkshop.dev. It's great to see you are working on this important problem. Would you like to have a call to discuss our approaches and see if there is an opportunity to collaborate?

**Comment by RandyMcMillan** [comment]
I will take a look at why ngit CI is failing.

**Comment by DanConwayDev** [comment]
Thanks very much for offering to do that! Just as you posted the message I applied a fix.

We have touched base and had some productive conversations so I'll close this issue.
