### ISSUE TITLE
error: ./template/gnostr-get-relays.c: No such file or directory

### ISSUE THREAD

**Issue by etjcoder** [gnostr-org/gnostr#71]
When running 'sudo make gnostr all', I received this error that terminated the compilation. 

```
Submodule path 'web/view': checked out 'a32bbd35bf59c058d2e91cd751e63e4e7a97a0ba'
cc ./template/gnostr-get-relays.c -o gnostr-get-relays
cc: error: ./template/gnostr-get-relays.c: No such file or directory
cc: fatal error: no input files
compilation terminated.
make: *** [gnostr.mk:180: gnostr-get-relays] Error 1
```

I checked the gnostr/template folder and only see "gnostr-set-relays.c" 

ls gnostr/template 
`
active_relays.sh  gnostr-blockheight  gnostr-git-send   gnostr-keyconv  gnostr-proxy-test    gnostr-syndication       loop.sh
bee.js            gnostr-e            gnostr-git-show   gnostr-nip      gnostr-query         gnostr-syndication-test  nostr_events.js
db_explore.js     gnostr-fs           gnostr-hexidrome  gnostr-nonce    gnostr-relays        gnostr-weeble            null
db.js             gnostr-functions    gnostr-iftop      gnostr-nvm      gnostr-send          gnostr-wobble            RELAYS.md
git-test1.sh      gnostr-get-relays   gnostr-init       gnostr-org      gnostr-set-relays    gnostr-xor               server.js
gnostr-add        gnostr-git-log      gnostr.js         gnostr-post     gnostr-set-relays.c  goodbye.js               swarm.js
gnostr-add.sh     gnostr-git-reflog   gnostr-jsmin.c    gnostr-proxy    gnostr-snapshot      log-reflog.diff          xor.sh
`
Do I need to update the Makefile? If so I can try that, however I can't find where the rule is located. I will look and report back. If anyone knows any reasons for this / quick fixes please let me know!

**Comment by etjcoder** [comment]
I pulled up the gnostr.mk file and looked at line 80. Looks like it's not a typo and there should be a file or folder in templates called gnostr-get-relay
![gnostrmk-line180](https://github.com/gnostr-org/gnostr/assets/50124701/51aedea8-9812-42ef-a228-59f8cda3a028)

**Comment by RandyMcMillan** [comment]
this ought to be fixed.
I am going to tag another release.
I will ping you when ready.

**Comment by RandyMcMillan** [comment]
https://github.com/gnostr-org/gnostr/releases/tag/v0.0.15
